# Generated by Django 4.1 on 2022-08-19 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pic', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('best_before_end', models.DateField()),
                ('amount_type', models.CharField(choices=[('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('oz', 'Ounce'), ('fl. oz', 'Fluid Ounce'), ('c', 'Cup'), ('qt', 'Quart'), ('pt', 'Pint'), ('gal', 'Gallon'), ('lb', 'Pound'), ('ml', 'Millilitre'), ('g', 'Gram'), ('kg', 'Kilogram'), ('l', 'Litre'), (' ', 'Nothing')], default=' ', max_length=6)),
            ],
        ),
    ]
